CREATE DATABASE offcode;

\c offcode;

CREATE TABLE usuarios (
    id_usuario SERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    username VARCHAR(20) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    senha VARCHAR(20) NOT NULL,
    tipo_conta VARCHAR(7) CHECK (tipo_conta IN ('Empresa', 'Pessoal')),
    foto_perfil TEXT,
    foto_capa TEXT,
    descricao VARCHAR(600),
    especializacoes TEXT
);

INSERT INTO usuarios (nome, username, email, senha, tipo_conta, foto_perfil, foto_capa, descricao, especializacoes) VALUES
('Vitor Cavalcanti', '@vitorcavalcanti', 'vitor.cavalcanti@devmail.com', '1234', 'Empresa', 'vitor.jpg', NULL, 'Especialista em APIs REST e arquitetura de microsservicos.', 'backend'),
('Otavio Pires', '@otaviopires', 'otavio.pires@codehub.dev', '1234', 'Empresa', 'otavio.jpg', NULL, 'Transformo ideias em solucoes web usando Node.js e React.', 'fullstack'),
('Enzo Almeida', '@enzoalmeida', 'enzo.almeida@devmail.com', '1234', 'Pessoal', 'enzo.jpg', NULL, 'Focado em escalabilidade e seguranca de sistemas.', 'backend'),
('Francisco Cavalcanti', '@franciscoc', 'francisco.c@codehub.dev', '1234', 'Empresa', 'francisco.jpg', NULL, 'Desenvolvedor apaixonado por testes automatizados e TDD.', 'qualidade'),
('Isabela Cavalcanti', '@isabelacaval', 'isabela.cavalcanti@devmail.com', '1234', 'Pessoal', 'isabela.jpg', NULL, 'Curiosa por UX, UI e acessibilidade na web.', 'frontend'),
('Marcela Rocha', '@marcelar', 'marcela.rocha@tech.dev', '1234', 'Pessoal', 'marcela.jpg', NULL, 'Desenvolvedora web em transicao para engenharia de dados.', 'dados'),
('Amanda Gomes', '@amandagomes', 'amanda.gomes@devmail.com', '1234', 'Empresa', 'amanda.jpg', NULL, 'Criadora de interfaces performaticas com React e Tailwind.', 'frontend'),
('Marcelo Correia', '@marcelodev', 'marcelo.correia@codehub.dev', '1234', 'Empresa', 'marcelo.jpg', NULL, 'DevOps com foco em CI/CD, Docker e Kubernetes.', 'devops'),
('Nicolas Correia', '@nicolasdev', 'nicolas.c@devmail.com', '1234', 'Pessoal', 'nicolas.jpg', NULL, 'Entusiasta de arquitetura hexagonal e DDD.', 'backend'),
('Diego Costa', '@diegocosta', 'diego.costa@tech.dev', '1234', 'Pessoal', 'diego.jpg', NULL, 'Estudando fullstack com foco em aplicacoes serverless.', 'fullstack'),
('Laura Fernandes', '@laurafernandes', 'laura.f@tech.dev', '1234', 'Pessoal', 'laura.jpg', NULL, 'Apaixonada por front-end e design de interfaces acessiveis.', 'frontend'),
('Eduardo Martins', '@eduardomartins', 'edu.martins@devmail.com', '1234', 'Empresa', 'eduardo.jpg', NULL, 'Full-stack developer com foco em aplicacoes escalaveis.', 'fullstack'),
('Juliana Souza', '@julianasouza', 'juliana.souza@codehub.dev', '1234', 'Pessoal', 'juliana.jpg', NULL, 'Explorando o mundo de APIs REST e microsservicos.', 'backend'),
('Rodrigo Nascimento', '@rodrigonascimento', 'rodrigo.ns@devmail.com', '1234', 'Empresa', 'rodrigo.jpg', NULL, 'DevOps e entusiasta de automacoes com CI/CD.', 'devops'),
('Camila Duarte', '@camiladuarte', 'camila.duarte@codehub.com', '1234', 'Pessoal', 'camila.jpg', NULL, 'Amante de codigo limpo e testes automatizados.', 'qualidade'),
('Lucas Almeida', '@lucasalmeida', 'lucas.almeida@devmail.com', '1234', 'Empresa', 'lucas.jpg', NULL, 'Especialista em seguranca de aplicacoes web.', 'seguranca'),
('Fernanda Lima', '@fernandalima', 'fernanda.lima@techmail.com', '1234', 'Pessoal', 'fernanda.jpg', NULL, 'Desenvolvedora mobile com foco em Flutter.', 'mobile'),
('Bruno Henrique', '@brunohenrique', 'bruno.henrique@devmail.com', '1234', 'Empresa', 'bruno.jpg', NULL, 'Transformando ideias em codigo funcional ha 5 anos.', 'fullstack'),
('Tatiane Rocha', '@tatianerocha', 'tatiane.rocha@codehub.com', '1234', 'Pessoal', 'tatiane.jpg', NULL, 'Data lover e especialista em SQL e analise de dados.', 'dados'),
('Rafael Mendes', '@rafaelmendes', 'rafael.mendes@devmail.com', '1234', 'Empresa', 'rafael.jpg', NULL, 'Backend focado em Node.js e mensageria com RabbitMQ.', 'backend'),
('Lucas Oliveira', '@lucasoliveira', 'lucas.oliveira@codehub.dev', '1234', 'Pessoal', 'lucas_o.jpg', NULL, 'Especialista em Vue.js e Vuex para SPAs.', 'frontend'),
('Bianca Lima', '@biancalima', 'bianca.lima@devmail.com', '1234', 'Empresa', 'bianca.jpg', NULL, 'Curiosa por analise preditiva com Python e pandas.', 'dados'),
('Felipe Ramos', '@feliperamos', 'felipe.ramos@tech.dev', '1234', 'Empresa', 'felipe.jpg', NULL, 'Engenheiro de software com foco em microsservicos.', 'backend'),
('Marina Freitas', '@marinafreitas', 'marina.freitas@codehub.dev', '1234', 'Pessoal', 'marina.jpg', NULL, 'Apaixonada por resolver bugs dificeis com calma e cafe.', 'debug'),
('Gabriel Cardoso', '@gabrielc', 'gabriel.cardoso@devmail.com', '1234', 'Empresa', 'gabriel.jpg', NULL, 'Desenvolvedor Ruby on Rails em busca de codigo limpo.', 'backend'),
('Natalia Moreira', '@natalia', 'natalia.moreira@techmail.com', '1234', 'Pessoal', 'natalia.jpg', NULL, 'Focada em acessibilidade e inclusao digital.', 'frontend'),
('Ricardo Dias', '@ricardodias', 'ricardo.dias@codehub.dev', '1234', 'Empresa', NULL, NULL, 'Dev mobile especialista em React Native.', 'mobile'),
('Bruna Santos', '@brunasantos', 'bruna.santos@tech.dev', '1234', 'Empresa', NULL, NULL, 'Explorando GraphQL e performance em APIs.', 'backend'),
('Joao Paulo', '@joaopaulo', 'joao.paulo@devmail.com', '1234', 'Pessoal', NULL, NULL, 'Apaixonado por algoritmos, estruturas de dados e Go.', 'backend'),
('Helena Mendes', '@helenamendes', 'helena.mendes@codehub.dev', '1234', 'Empresa', NULL, NULL, 'Dev front-end focada em design responsivo e boas praticas.', 'frontend'),
('Andre Souza', '@andresouza', 'andre.souza@devmail.com', '1234', 'Pessoal', NULL, NULL, 'Trabalho com automacoes Python e web scraping.', 'automacao'),
('Sofia Matos', '@sofiamatos', 'sofia.matos@codehub.dev', '1234', 'Empresa', NULL, NULL, 'Especialista em testes E2E com Cypress e Playwright.', 'qualidade'),
('Thiago Barbosa', '@thiagob', 'thiago.barbosa@tech.dev', '1234', 'Pessoal', NULL, NULL, 'Dev backend com interesse em arquiteturas event-driven.', 'backend'),
('Leticia Andrade', '@leticiaandrade', 'leticia.andrade@devmail.com', '1234', 'Empresa', NULL, NULL, 'Desenvolvedora apaixonada por educacao tech.', 'educacao'),
('Renan Pereira', '@renanpereira', 'renan.pereira@codehub.dev', '1234', 'Empresa', NULL, NULL, 'Especialista em APIs publicas e autenticacao OAuth2.', 'backend'),
('Aline Ribeiro', '@alineribeiro', 'aline.ribeiro@techmail.com', '1234', 'Pessoal', NULL, NULL, 'Criadora de dashboards interativos com React + Chart.js.', 'frontend'),
('Pedro Henrique', '@pedrohdev', 'pedro.henrique@devmail.com', '1234', 'Empresa', NULL, NULL, 'Fa de containers, escalabilidade e pipelines.', 'devops'),
('Juliana Lima', '@julianalima', 'juliana.lima@tech.dev', '1234', 'Empresa', NULL, NULL, 'Trabalho com arquitetura limpa e Clean Code.', 'fullstack'),
('Murilo Vieira', '@murilovieira', 'murilo.vieira@codehub.dev', '1234', 'Pessoal', NULL, NULL, 'Interessado em DDD e testes de integracao.', 'backend'),
('Vitoria Cruz', '@vitoriacruz', 'vitoria.cruz@techmail.com', '1234', 'Pessoal', NULL, NULL, 'Foco em design de experiencia e performance front-end.', 'frontend'),
('Henrique Lopes', '@henriquelopes', 'henrique.lopes@devmail.com', '1234', 'Empresa', NULL, NULL, 'Back-end developer com amor por APIs performaticas.', 'backend'),
('Giovanna Teixeira', '@giovannateixeira', 'giovanna.teixeira@codehub.dev', '1234', 'Pessoal', NULL, NULL, 'Especialista em refatoracao de codigo legado.', 'qualidade'),
('Caio Martins', '@caiomartins', 'caio.martins@techmail.com', '1234', 'Pessoal', NULL, NULL, 'Estudante de ciencia da computacao e Pythonista raiz.', 'backend'),
('Beatriz Silva', '@beatrizsilva', 'beatriz.silva@devmail.com', '1234', 'Empresa', NULL, NULL, 'Desenvolvedora com foco em inclusao e tech acessivel.', 'frontend'),
('Danilo Moreira', '@danilomoreira', 'danilo.moreira@codehub.dev', '1234', 'Empresa', NULL, NULL, 'Dev apaixonado por codigo limpo e performance.', 'backend'),
('Patricia Moura', '@patriciamoura', 'patricia.moura@techmail.com', '1234', 'Pessoal', NULL, NULL, 'Criadora de conteudo sobre JavaScript e carreira dev.', 'educacao'),
('Alan Fernandes', '@alanfernandes', 'alan.fernandes@devmail.com', '1234', 'Empresa', NULL, NULL, 'Desenvolvedor backend especializado em autenticacao.', 'backend'),
('Livia Gomes', '@liviagomes', 'livia.gomes@codehub.dev', '1234', 'Pessoal', NULL, NULL, 'Frontend focada em performance e web mobile first.', 'frontend'),
('Cesar Oliveira', '@cesardev', 'cesar.oliveira@techmail.com', '1234', 'Empresa', NULL, NULL, 'Entusiasta de C# e clean architecture.', 'backend'),
('Elaine Ferreira', '@elaineferreira', 'elaine.ferreira@devmail.com', '1234', 'Pessoal', NULL, NULL, 'Desenvolvedora apaixonada por comunidades de codigo aberto.', 'opensource'),
('Ana Carolina', '@anacarolina', 'anacarol@devmail.com', '1234', 'Pessoal', 'anac.jpg', NULL, 'Desenvolvedora apaixonada por comunidades de codigo aberto.', 'opensource'),
('Ana Julia', '@anajulia', 'anaju@devmail.com', '1234', 'Pessoal', 'anaj.jpg', NULL, 'Desenvolvedora apaixonada por comunidades de codigo aberto.', 'opensource'),
('Beatriz Lima', '@bea', 'bea@devmail.com', '1234', 'Pessoal', 'bea.jpg', NULL, 'Desenvolvedora apaixonada por comunidades de codigo aberto.', 'opensource'),
('Luana Domeneghetti', '@domeneghettii', 'domeneghettii@devmail.com', '1234', 'Pessoal', 'luana.jpg', NULL, 'Desenvolvedora apaixonada por comunidades de codigo aberto.', 'opensource'),
('Caio Lacerda', '@caiodev', 'caio@devmail.com', '1234', 'Pessoal', 'caio.jpg', NULL, 'Especialista em APIs REST e arquitetura de microsservicos.', 'backend'),
('Bernardo Marques', '@bernardo', 'bernardo@devmail.com', '1234', 'Pessoal', 'bernardo.jpg', NULL, 'Especialista em APIs REST e arquitetura de microsservicos.', 'backend');

CREATE TABLE posts (
    id_post SERIAL PRIMARY KEY,
    id_usuario INT NOT NULL, 
    conteudo_post TEXT NOT NULL,
    anexo TEXT, 
    data_publicacao DATE,
    CONSTRAINT fk_usuario_post FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);


INSERT INTO posts (id_usuario, conteudo_post, anexo, data_publicacao) VALUES

(1, 'Organizei minha primeira REST API com Node.js e Express! Quem quiser feedback, estou aceitando dicas!', NULL, '2025-04-14'),
(2, 'Como voces organizam suas pastas em projetos React? To tentando deixar mais limpo possivel.', NULL, '2025-04-12'),
(3, 'Nao aguento mais mexer com CSS. Flexbox me odeia, certeza.', NULL, '2025-04-13'),
(3, 'Finalizei meu portfolio com HTML, CSS e um pouquinho de JS. To orgulhoso!', NULL, '2025-04-16'),
(4, 'Docker mudou minha vida. Um caminho sem volta!', NULL, '2025-04-11'),
(4, 'Configurei CI/CD com GitHub Actions, e foi mais facil do que achei.', NULL, '2025-04-13'),
(4, 'Vale a pena investir tempo em testes unitarios logo no comeco?', NULL, '2025-04-17'),
(5, 'Primeira experiencia com TypeScript e... to apaixonado!', NULL, '2025-04-10'),
(5, 'Trabalhando com banco relacional pela primeira vez. PostgreSQL ta sendo uma boa escolha.', NULL, '2025-04-14'),
(6, 'Que framework back-end voces recomendam alem do Express?', NULL, '2025-04-12'),
(6, 'Desenvolvi um CRUD simples com Sequelize. Curti bastante!', NULL, '2025-04-15'),
(7, 'Tem alguma extensao VS Code indispensavel pra quem trabalha com front-end?', NULL, '2025-04-13'),
(7, 'Fiz uma tela de login com React + Tailwind. Ficou clean demais!', NULL, '2025-04-14'),
(8, 'Finalmente entendi como Promises funcionam de verdade! 🎉', NULL, '2025-04-12'),
(8, 'Alguem mais demora 10x mais pra fazer a responsividade do que o resto?', NULL, '2025-04-13'),
(9, 'Iniciei um curso de seguranca da informacao. O buraco e MUITO mais embaixo...', NULL, '2025-04-11'),
(9, 'Usei bcrypt pela primeira vez pra criptografar senhas. Importante demais!', NULL, '2025-04-14'),
(10, 'Montei meu primeiro servidor VPS com Ubuntu. Que sensacao de poder! 😄', NULL, '2025-04-10'),
(10, 'Alguem ja automatizou deploy com Git hooks? Recomendacoes?', NULL, '2025-04-13'),
(11, 'Depois de dias brigando, minha aplicacao finalmente roda com HTTPS! 🚀', NULL, '2025-04-12'),
(11, 'Como voces fazem autenticacao com refresh token?', NULL, '2025-04-15'),
(12, 'Usar GraphQL me deixou confuso, mas agora to comecando a ver as vantagens.', NULL, '2025-04-13'),
(12, 'Qual sua stack preferida pro front-end hoje?', NULL, '2025-04-14'),
(13, 'Me recomendam comecar estudando Clean Architecture agora ou mais pra frente?', NULL, '2025-04-12'),
(13, 'Implementando dark mode no site: desafio ou tortura?', NULL, '2025-04-13'),
(14, 'Alguem usa Prisma aqui? To considerando trocar pelo Sequelize.', NULL, '2025-04-12'),
(14, 'Fiz uma API em 2 horas que antes levava 2 dias. Aprender direito e tudo.', NULL, '2025-04-15'),
(15, 'Que orgulho: meu primeiro app foi pra Play Store hoje!', NULL, '2025-04-10'),
(15, 'Quais as melhores praticas de versionamento semantico que voces seguem?', NULL, '2025-04-13'),
(16, 'To brincando com WebSockets. Incrivel ver as coisas em tempo real!', NULL, '2025-04-12'),
(16, 'Como lidar com erros HTTP no front de forma elegante?', NULL, '2025-04-14'),
(17, 'Minhas funcoes estavam com 150 linhas. Refatorei tudo em 10 pequenas.', NULL, '2025-04-11'),
(17, 'Voce usa ESLint no seu projeto? Faz diferenca real no dia a dia?', NULL, '2025-04-13'),
(18, 'Rodar testes automatizados salvou meu app de um bug feio hoje.', NULL, '2025-04-10'),
(18, 'Gosto de pensar em codigo como poesia legivel. Alguem mais?', NULL, '2025-04-12'),
(19, 'Subi meu primeiro projeto fullstack com Docker Compose. Muito pratico!', NULL, '2025-04-13'),
(19, 'Nao sei viver sem Postman. Obrigado a quem criou.', NULL, '2025-04-14'),
(20, 'Comecei um projeto pessoal com Next.js. Performance incrivel!', NULL, '2025-04-12'),
(20, 'Alguem recomenda boas praticas pra SEO em apps React?', NULL, '2025-04-14'),
(21, 'Acabei de aprender sobre injecao de dependencia em Node.js. Nunca pensei que ia gostar tanto.', NULL, '2025-04-15'),
(21, 'Refatorei um projeto inteiro pra usar TypeScript. Valeu cada segundo!', NULL, '2025-04-16'),
(22, 'Qual banco NoSQL voces preferem: MongoDB ou Firebase?', NULL, '2025-04-13'),
(22, 'To criando uma API REST so com funcoes serverless. Muito diferente do que to acostumado.', NULL, '2025-04-15'),
(23, 'Finalmente entendi como usar Git rebase sem destruir tudo. Vitoria pessoal.', NULL, '2025-04-12'),
(23, 'Automatizei tarefas com npm scripts. Pequenos habitos que salvam tempo.', NULL, '2025-04-14'),
(24, 'Meu front-end ta comecando a conversar com o back-end! 🎉', NULL, '2025-04-11'),
(24, 'Implementar autenticacao JWT foi mais facil do que achei.', NULL, '2025-04-13'),
(25, 'Aprender regex foi dificil, mas agora me sinto um hacker.', NULL, '2025-04-12'),
(25, 'Voces usam testes end-to-end? Ou so unitarios ja ajudam bastante?', NULL, '2025-04-14'),
(26, 'Me peguei refatorando codigo as 3h da manha. Coisa de dev mesmo.', NULL, '2025-04-10'),
(26, 'Alguem tem dicas de produtividade pra quem trabalha com front e back ao mesmo tempo?', NULL, '2025-04-13'),
(27, 'Usei Tailwind pela primeira vez. Que liberdade! 😍', NULL, '2025-04-14'),
(27, 'Deploy com Vercel e realmente tao facil quanto dizem.', NULL, '2025-04-16'),
(28, 'Como voces lidam com multiplos ambientes (dev, staging, prod)?', NULL, '2025-04-12'),
(28, 'Dockerizando tudo aqui. Ate o cafe ta vindo em container.', NULL, '2025-04-14'),
(29, 'Redirecionei tudo com NGINX e aprendi mais em 2h do que num curso inteiro.', NULL, '2025-04-10'),
(29, 'Vale a pena usar Redis pra sessoes? O que acham?', NULL, '2025-04-13'),
(30, 'Hoje percebi o poder do Git stash. Salvou minha branch! 😂', NULL, '2025-04-12'),
(30, 'Como voces fazem logs no back-end de producao?', NULL, '2025-04-15'),
(31, 'To explorando GraphQL com Apollo. Bem intuitivo ate agora.', NULL, '2025-04-14'),
(31, 'Alguem tem template de arquitetura de projeto Node.js pra compartilhar?', NULL, '2025-04-15'),
(32, 'Primeira API publica que fiz teve mais de 1.000 requisicoes hoje. Que emocao!', NULL, '2025-04-12'),
(32, 'Se eu tivesse testado antes, nao teria quebrado producao hoje.', NULL, '2025-04-14'),
(33, 'Qual IDE voce nao vive sem? Eu sou fiel ao VS Code.', NULL, '2025-04-13'),
(33, 'Entendi como funciona cache no navegador. To comecando a amar o DevTools.', NULL, '2025-04-15'),
(34, 'Nunca mais subestimo os beneficios do codigo limpo. Claridade e tudo.', NULL, '2025-04-12'),
(34, 'Ja colocaram analytics em projeto pessoal? Vale a pena?', NULL, '2025-04-14'),
(35, 'Publiquei meu primeiro pacote no npm hoje. Um marco!', NULL, '2025-04-10'),
(35, 'Montei um sistema de agendamento com cron + Node. Funciona que e uma beleza.', NULL, '2025-04-13'),
(36, 'Reescrevendo codigo legado... tem que ter paciencia e cafe.', NULL, '2025-04-12'),
(36, 'Versao 2.0 do meu app esta no ar! Redesenhado e reestruturado.', NULL, '2025-04-14'),
(37, 'Pra quem e dev iniciante, recomendo comecar com projetos reais. Voce aprende 10x mais.', NULL, '2025-04-13'),
(37, 'Fiz uma API com NestJS e fiquei surpreso com a organizacao.', NULL, '2025-04-15'),
(38, 'Lutei com CORS por 3 dias. Venci, mas perdi a paz.', NULL, '2025-04-12'),
(38, 'Quem usa Swagger pra documentar API? Muito util.', NULL, '2025-04-14'),
(39, 'Transformei uma planilha em uma aplicacao web completa. Cliente feliz = dev feliz.', NULL, '2025-04-13'),
(39, 'Adicionei testes com Jest e a confianca no codigo aumentou 200%.', NULL, '2025-04-15'),
(40, 'React Native me surpreendeu pela facilidade. Ja to pensando no segundo app.', NULL, '2025-04-11'),
(40, 'Alguem usa Flutter? Como compara com React Native?', NULL, '2025-04-14'),
(41, 'Depois de estudar SOLID, meu codigo ficou outro.', NULL, '2025-04-12'),
(41, 'Alguem tem dicas pra comecar com TDD?', NULL, '2025-04-15'),
(42, 'Implementei autenticacao com OAuth 2.0. Um mundo novo!', NULL, '2025-04-13'),
(42, 'Voce faz backup do banco com que frequencia?', NULL, '2025-04-14'),
(43, 'Dica do dia: use .env SEMPRE. Nunca coloque credenciais direto no codigo.', NULL, '2025-04-12'),
(43, 'Erros bobos viram gigantes se voce nao versiona o codigo direito.', NULL, '2025-04-14'),
(44, 'Estou viciado em fazer mini projetos no CodePen.', NULL, '2025-04-13'),
(44, 'Sass ou Tailwind? Debate da semana.', NULL, '2025-04-15'),
(45, 'PostgreSQL + Prisma = amor eterno.', NULL, '2025-04-12'),
(45, 'Voce usa migrations manuais ou automaticas?', NULL, '2025-04-14'),
(46, 'Descobri que documentacao salva vidas. Literalmente.', NULL, '2025-04-11'),
(46, 'Meu app so funcionava em local porque esqueci a porta no .env. 😂', NULL, '2025-04-13'),
(47, 'D3.js e incrivel, mas a curva de aprendizado e real.', NULL, '2025-04-12'),
(47, 'Dashboard responsivo finalizado! Que orgulho!', NULL, '2025-04-14'),
(48, 'Usar zod + tRPC esta virando padrao por aqui.', NULL, '2025-04-13'),
(48, 'Como voces fazem controle de versao de dependencias?', NULL, '2025-04-15'),
(49, 'PWA e o futuro? To gostando da experiencia.', NULL, '2025-04-12'),
(49, 'Meu app agora funciona offline. Nunca pensei que conseguiria.', NULL, '2025-04-14'),
(50, 'Iniciei uma mentoria pra devs junior. Muito gratificante.', NULL, '2025-04-13'),
(50, 'Refatorei um monolito em microservicos. Agora entendo a complexidade real disso.', NULL, '2025-04-15'),
(51, 'Mostre seu design UX/UI favorito! Eu comeco:', 'ux-ui.jpg', '2025-06-03'),
(52, 'Comecei a usar o Figma para prototipos interativos!', 'interface-do-figma.jpg', '2025-06-03'),
(53, 'Qual a melhor forma de organizar componentes React em projetos grandes?', 'meme-pastas.jpg', '2025-06-04'),
(54, 'Tava sempre me perdendo com os componentes do React, entao criei um repositorio com varios deles', 'components-react.png', '2025-06-04'),
(55, 'Descobri hoje que da pra usar `COALESCE` pra evitar `NULL` no SQL. Nunca mais uso `IFNULL` errado.', NULL, '2025-04-10'),
(56, 'Alguem ja usou Zustand no lugar do Redux? Vale a pena?', NULL, '2025-04-15');


CREATE TABLE duvidas (
    id_post SERIAL PRIMARY KEY,
    id_usuario INT NOT NULL, 
    conteudo_duvida TEXT NOT NULL,
    anexo TEXT, 
    data_publicacao DATE,
    CONSTRAINT fk_usuario_post FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);

INSERT INTO duvidas (id_usuario, conteudo_duvida, anexo, data_publicacao) VALUES
(1, 'Como faco para melhorar a performance de uma query SQL complexa?', NULL, '2025-04-25'),
(1, 'Indices em colunas JSON valem a pena no PostgreSQL?', NULL, '2025-04-26'),
(2, 'Alguem sabe como configurar um servidor Node.js para producao?', NULL, '2025-04-26'),
(2, 'Vale a pena usar PM2 em todos os ambientes?', NULL, '2025-04-27'),
(3, 'Qual a melhor pratica para versionar um banco de dados?', NULL, '2025-04-27'),
(3, 'Flyway ou Liquibase? Qual voces preferem e por que?', NULL, '2025-04-28'),
(4, 'Como lidar com conflitos de merge no Git?', NULL, '2025-04-28'),
(4, 'E melhor fazer rebase ou merge em branches grandes?', NULL, '2025-04-29'),
(5, 'Qual a diferenca entre REST e GraphQL?', NULL, '2025-04-29'),
(5, 'GraphQL e indicado para sistemas simples?', NULL, '2025-04-30'),
(6, 'Como faco para debugar um erro intermitente em uma aplicacao?', NULL, '2025-04-30'),
(6, 'Vale a pena investir tempo em logs estruturados desde o inicio?', NULL, '2025-05-01'),
(7, 'Como lidar com cache em aplicacoes que usam dados em tempo real?', NULL, '2025-05-02'),
(7, 'Existe alguma estrategia melhor que cache-control para front-end?', NULL, '2025-05-03'),
(8, 'Qual a melhor forma de organizar um projeto grande em React?', NULL, '2025-05-04'),
(8, 'Voces usam Atomic Design? O que acham dele?', NULL, '2025-05-05'),
(9, 'E possivel aplicar TDD com eficiencia em projetos de backend?', NULL, '2025-05-06'),
(9, 'Quais ferramentas voces usam para testes automatizados em Node?', NULL, '2025-05-07'),
(10, 'Como evitar acoplamento excessivo entre servicos?', NULL, '2025-05-08'),
(10, 'Mensageria (RabbitMQ, Kafka) ajuda nesse problema?', NULL, '2025-05-09'),
(11, 'Como voces organizam arquivos estaticos em aplicacoes Node?', NULL, '2025-05-10'),
(11, 'Tem algum padrao para isso em projetos grandes?', NULL, '2025-05-11'),
(12, 'Como lidar com uploads de arquivos grandes no back-end?', NULL, '2025-05-12'),
(12, 'Vale a pena usar streaming de uploads ao inves de salvar direto?', NULL, '2025-05-13'),
(13, 'Qual o melhor lugar para colocar as validacoes no back-end?', NULL, '2025-05-14'),
(13, 'Bibliotecas como Yup ou Zod sao recomendadas no back tambem?', NULL, '2025-05-15'),
(14, 'Voces preferem usar ORMs como Sequelize ou query builders?', NULL, '2025-05-16'),
(14, 'Vale a pena aprender SQL puro mesmo usando ORM?', NULL, '2025-05-17'),
(15, 'Como montar testes automatizados para endpoints protegidos?', NULL, '2025-05-18'),
(15, 'Autenticacao com JWT atrapalha testes automatizados?', NULL, '2025-05-19'),
(16, 'Como voces organizam as rotas de APIs publicas e privadas?', NULL, '2025-05-20'),
(16, 'Tem algum padrao pra middlewares de autenticacao no Express?', NULL, '2025-05-21'),
(17, 'Em apps React, voces usam styled-components ou Tailwind?', NULL, '2025-05-22'),
(17, 'Qual a vantagem real do Tailwind num projeto grande?', NULL, '2025-05-23'),
(18, 'Como lidar com dependencias desatualizadas em projetos antigos?', NULL, '2025-05-24'),
(18, 'Voces usam alguma ferramenta de verificacao automatica?', NULL, '2025-05-25'),
(19, 'Como separar responsabilidades entre controller e service no backend?', NULL, '2025-05-26'),
(19, 'E exagero aplicar DDD em apps pequenos?', NULL, '2025-05-27'),
(20, 'Como aplicar autenticacao OAuth2 em aplicacoes web?', NULL, '2025-05-28'),
(20, 'OAuth2 e exagerado para aplicacoes internas?', NULL, '2025-05-29'),
(21, 'Qual a melhor estrategia para lidar com autenticacao usando tokens JWT em microservicos?', NULL, '2025-04-17'),
(21, 'E seguro armazenar refresh tokens no localStorage?', NULL, '2025-04-18'),
(22, 'Como lidar com multiplos estados em aplicacoes React complexas?', NULL, '2025-04-17'),
(22, 'Vale a pena usar Zustand no lugar de Redux?', NULL, '2025-04-19'),
(23, 'Como faco testes de integracao entre microservicos usando Node.js?', NULL, '2025-04-20'),
(23, 'Diferenca entre testes unitarios e testes de contrato?', NULL, '2025-04-21'),
(24, 'Qual melhor forma de fazer deploy continuo em apps com Docker?', NULL, '2025-04-20'),
(24, 'Como manter variaveis de ambiente seguras no CI/CD?', NULL, '2025-04-22'),
(25, 'Como organizar melhor minhas rotas em uma API REST com Express?', NULL, '2025-04-21'),
(25, 'Vale a pena usar uma arquitetura em camadas mesmo em projetos pequenos?', NULL, '2025-04-23'),
(26, 'Existe alguma ferramenta que detecta code smells automaticamente?', NULL, '2025-04-18'),
(26, 'Qual plugin do ESLint voce mais recomenda para projetos JavaScript?', NULL, '2025-04-19'),
(27, 'Estou tendo problemas com CORS em APIs publicas. Alguma solucao definitiva?', NULL, '2025-04-20'),
(27, 'E seguro usar "*" no Access-Control-Allow-Origin?', NULL, '2025-04-22'),
(28, 'Como gerenciar multiplos contextos em React de forma eficiente?', NULL, '2025-04-21'),
(28, 'Diferenca real entre Context API e Redux Toolkit?', NULL, '2025-04-23'),
(29, 'Como montar um ambiente local com multiplos servicos usando Docker Compose?', NULL, '2025-04-17'),
(29, 'Tem como versionar arquivos .env de forma segura?', NULL, '2025-04-18'),
(30, 'Qual estrutura de pastas e mais recomendada para apps Node.js grandes?', NULL, '2025-04-19'),
(30, 'Vale a pena isolar cada funcionalidade em modulos separados?', NULL, '2025-04-20'),
(31, 'Como usar Apollo Client com multiplas queries simultaneas?', NULL, '2025-04-21'),
(31, 'GraphQL tem cache automatico? Como configurar?', NULL, '2025-04-22'),
(32, 'Como voces monitoram a performance de APIs em producao?', NULL, '2025-04-23'),
(32, 'Tem alguma ferramenta gratuita para profiling de Node.js?', NULL, '2025-04-24'),
(33, 'Como lidar com branches longas que ficam defasadas do main?', NULL, '2025-04-19'),
(33, 'Rebase ou merge: o que preferem e por que?', NULL, '2025-04-20'),
(34, 'E possivel usar Firebase apenas como backend para apps React?', NULL, '2025-04-21'),
(34, 'Firebase Firestore ou Realtime Database? Qual usar?', NULL, '2025-04-22'),
(35, 'Como fazer rollback automatico em caso de falha no deploy?', NULL, '2025-04-18'),
(35, 'Ferramentas recomendadas para deploy zero downtime?', NULL, '2025-04-19'),
(36, 'O que considerar antes de aplicar microservicos em um projeto?', NULL, '2025-04-20'),
(36, 'Microservicos realmente valem a complexidade?', NULL, '2025-04-21'),
(37, 'Qual melhor forma de aprender estrutura de dados como dev web?', NULL, '2025-04-22'),
(37, 'Estrutura de dados afeta performance de APIs?', NULL, '2025-04-23'),
(38, 'Quando usar debounce e throttle em aplicacoes React?', NULL, '2025-04-18'),
(38, 'Lidando com multiplas requisicoes seguidas em tempo real. Alguma dica?', NULL, '2025-04-19'),
(39, 'Vale a pena aprender DevOps mesmo sendo so dev front-end?', NULL, '2025-04-20'),
(39, 'Quais ferramentas basicas de DevOps devo dominar primeiro?', NULL, '2025-04-22'),
(40, 'Como melhorar o tempo de carregamento de apps React Native?', NULL, '2025-04-21'),
(40, 'Diferenca entre FlatList e ScrollView? Qual usar?', NULL, '2025-04-23'),
(41, 'Testes unitarios em APIs REST realmente ajudam?', NULL, '2025-04-17'),
(41, 'Como configurar Jest para testes assincronos?', NULL, '2025-04-18'),
(42, 'Qual padrao usar para organizacao de middlewares em Express?', NULL, '2025-04-19'),
(42, 'Diferenca entre middlewares sincronos e assincronos?', NULL, '2025-04-21'),
(43, 'Como lidar com autenticacao baseada em roles?', NULL, '2025-04-22'),
(43, 'Voce centraliza as permissoes ou distribui por endpoint?', NULL, '2025-04-24'),
(44, 'Existe alguma boa alternativa ao Redux Toolkit mais leve?', NULL, '2025-04-20'),
(44, 'Vale a pena usar Zustand ou Jotai em apps medios?', NULL, '2025-04-22'),
(45, 'E possivel migrar banco de dados com zero downtime?', NULL, '2025-04-19'),
(45, 'Prisma pode ser usado em ambiente serverless?', NULL, '2025-04-21'),
(46, 'Como manter a consistencia entre front e back com tipos compartilhados?', NULL, '2025-04-17'),
(46, 'Vale a pena usar zod + tRPC em apps fullstack?', NULL, '2025-04-19'),
(47, 'Como criar visualizacoes em tempo real com D3.js?', NULL, '2025-04-21'),
(47, 'Tem como otimizar graficos grandes em D3 sem travar o navegador?', NULL, '2025-04-23'),
(48, 'Como controlar versoes de dependencias sem quebrar builds antigos?', NULL, '2025-04-18'),
(48, 'Qual estrategia voces usam para gerenciar changelog de libs proprias?', NULL, '2025-04-20'),
(49, 'Quais cuidados tomar ao criar PWA com suporte offline?', NULL, '2025-04-21'),
(49, 'E possivel usar service workers em apps com rotas dinamicas?', NULL, '2025-04-22'),
(50, 'Como comecar a aplicar arquitetura hexagonal em projetos reais?', NULL, '2025-04-20'),
(50, 'Qual a melhor estrutura de pastas para manter dominios separados?', NULL, '2025-04-21'),
(2, NULL, 1, 'Uma dica para melhorar queries SQL complexas é usar EXPLAIN ANALYZE para identificar gargalos.', NULL, '2025-06-01'),
(3, NULL, 2, 'Índices em colunas JSON podem ajudar, mas avalie o uso real antes de criar.', NULL, '2025-06-01'),
(4, NULL, 3, 'Para produção, sempre use variáveis de ambiente e um gerenciador de processos como PM2.', NULL, '2025-06-01'),
(5, NULL, 4, 'PM2 é ótimo para produção, mas em dev pode ser exagero.', NULL, '2025-06-01'),
(6, NULL, 5, 'Versione o banco com ferramentas como Flyway ou Liquibase para manter controle.', NULL, '2025-06-01'),
(7, NULL, 6, 'Prefiro Flyway pela simplicidade, mas Liquibase é mais flexível.', NULL, '2025-06-01'),
(8, NULL, 7, 'Sempre faça backup antes de resolver conflitos de merge no Git.', NULL, '2025-06-01'),
(9, NULL, 8, 'Para branches grandes, prefiro rebase para manter o histórico limpo.', NULL, '2025-06-01'),
(10, NULL, 9, 'REST é mais simples, mas GraphQL oferece mais flexibilidade.', NULL, '2025-06-01'),
(11, NULL, 10, 'GraphQL pode ser usado em sistemas simples, mas avalie a complexidade.', NULL, '2025-06-01'),
(12, NULL, 11, 'Para debugar erros intermitentes, invista em logs detalhados.', NULL, '2025-06-01'),
(13, NULL, 12, 'Logs estruturados facilitam muito a análise de problemas.', NULL, '2025-06-01'),
(14, NULL, 13, 'Use cache TTL curto para dados em tempo real.', NULL, '2025-06-01'),
(15, NULL, 14, 'Além de cache-control, avalie uso de SWR ou React Query no front.', NULL, '2025-06-01'),
(16, NULL, 15, 'Organize projetos React por domínio ou feature.', NULL, '2025-06-01'),
(17, NULL, 16, 'Atomic Design ajuda na escalabilidade de projetos grandes.', NULL, '2025-06-01'),
(18, NULL, 17, 'TDD é eficiente, mas exige disciplina e prática.', NULL, '2025-06-01'),
(19, NULL, 18, 'Uso Jest e Supertest para testes automatizados em Node.', NULL, '2025-06-01'),
(20, NULL, 19, 'Evite acoplamento usando interfaces e eventos.', NULL, '2025-06-01'),
(21, NULL, 20, 'Mensageria como RabbitMQ ou Kafka ajuda a desacoplar serviços.', NULL, '2025-06-01'),
(22, NULL, 21, 'Organize arquivos estáticos por tipo em uma pasta pública.', NULL, '2025-06-01'),
(23, NULL, 22, 'Em projetos grandes, siga um padrão de organização para arquivos estáticos.', NULL, '2025-06-01'),
(24, NULL, 23, 'Para uploads grandes, prefira streaming para evitar timeout.', NULL, '2025-06-01'),
(25, NULL, 24, 'Streaming é melhor para uploads, pois consome menos memória.', NULL, '2025-06-01'),
(26, NULL, 25, 'Validações podem ficar no service, mas valide também no controller.', NULL, '2025-06-01'),
(27, NULL, 26, 'Yup e Zod são ótimas opções para validação no back-end.', NULL, '2025-06-01'),
(28, NULL, 27, 'Prefiro Sequelize pela praticidade, mas query builders dão mais controle.', NULL, '2025-06-01'),
(29, NULL, 28, 'Saber SQL puro é importante mesmo usando ORM.', NULL, '2025-06-01'),
(30, NULL, 29, 'Para testar endpoints protegidos, use mocks de autenticação.', NULL, '2025-06-01'),
(31, NULL, 30, 'JWT pode dificultar testes, mas é possível mockar tokens.', NULL, '2025-06-01'),
(32, NULL, 31, 'Separe rotas públicas e privadas em arquivos diferentes.', NULL, '2025-06-01'),
(33, NULL, 32, 'Padronize middlewares de autenticação para facilitar manutenção.', NULL, '2025-06-01'),
(34, NULL, 33, 'Prefiro styled-components pela flexibilidade, mas Tailwind é mais rápido.', NULL, '2025-06-01'),
(35, NULL, 34, 'Tailwind facilita a padronização visual em projetos grandes.', NULL, '2025-06-01'),
(36, NULL, 35, 'Para dependências desatualizadas, use ferramentas como Dependabot.', NULL, '2025-06-01'),
(37, NULL, 36, 'Ferramentas como SonarQube ajudam na verificação automática.', NULL, '2025-06-01'),
(38, NULL, 37, 'Separe controller e service para manter o código limpo.', NULL, '2025-06-01'),
(39, NULL, 38, 'DDD pode ser exagero em apps pequenos, mas traz benefícios.', NULL, '2025-06-01'),
(40, NULL, 39, 'OAuth2 é indicado para apps web que precisam de segurança.', NULL, '2025-06-01'),
(41, NULL, 40, 'Para apps internos, OAuth2 pode ser exagerado.', NULL, '2025-06-01'),
(42, NULL, 41, 'Use JWT com expiração curta e valide em cada microserviço.', NULL, '2025-06-01'),
(43, NULL, 42, 'Evite armazenar refresh tokens no localStorage, prefira cookies HttpOnly.', NULL, '2025-06-01'),
(44, NULL, 43, 'Gerencie múltiplos estados em React usando Context API ou Redux.', NULL, '2025-06-01'),
(45, NULL, 44, 'Zustand é mais simples que Redux, vale testar.', NULL, '2025-06-01'),
(46, NULL, 45, 'Para testes de integração entre microserviços, use test doubles e ambientes isolados.', NULL, '2025-06-01'),
(47, NULL, 46, 'Testes de contrato garantem integração entre serviços, diferente dos unitários.', NULL, '2025-06-01'),
(48, NULL, 47, 'Para deploy contínuo com Docker, use pipelines automatizados.', NULL, '2025-06-01'),
(49, NULL, 48, 'No CI/CD, mantenha variáveis de ambiente seguras usando secrets.', NULL, '2025-06-01'),
(50, NULL, 49, 'Organize rotas do Express por módulos para facilitar manutenção.', NULL, '2025-06-01');



CREATE TABLE comentarios (
    id_comentario SERIAL PRIMARY KEY,
    id_usuario INT NOT NULL,
    id_post INT,
    id_duvida INT,
    conteudo_comentario TEXT NOT NULL,
    anexo TEXT, 
    data_publicacao DATE,
    CONSTRAINT fk_usuario_comentario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_post_comentario FOREIGN KEY (id_post) REFERENCES posts(id_post) ON DELETE CASCADE
);

INSERT INTO comentarios (id_usuario, id_post, id_duvida, conteudo_comentario, anexo, data_publicacao) VALUES
(2, 1, NULL, 'Uso EXPLAIN ANALYZE direto quando a query parece lenta. Ja salvou minha vida.', NULL, '2025-06-01'),
(3, 1, NULL, 'Indice composto tambem pode ajudar bastante, dependendo da clausula WHERE.', NULL, '2025-06-02'),
(4, 2, NULL, 'Ja tive dor de cabeca configurando o PM2 com nginx. Mas valeu a pena.', NULL, '2025-06-03'),
(5, 2, NULL, 'Tenta usar o ecosystem.config.js do PM2, facilita demais.', NULL, '2025-06-04'),
(6, 3, NULL, 'Uso Flyway com sucesso faz tempo. Liquibase achei muito verboso.', NULL, '2025-06-05'),
(7, 4, NULL, 'Se o merge ta muito complexo, prefiro rebase pra manter o historico limpo.', NULL, '2025-06-06'),
(8, 4, NULL, 'Uso os dois, mas merge em branches de time e rebase nos pessoais.', NULL, '2025-06-06'),
(9, 5, NULL, 'GraphQL e legal, mas acho overkill pra CRUD simples.', NULL, '2025-06-07'),
(10, 6, NULL, 'Ja perdi horas com bug que so aparece em producao. Logs sao tudo.', NULL, '2025-06-08'),
(11, 6, NULL, 'Log estruturado com Elastic Stack me salvou num projeto grande.', NULL, '2025-06-08'),
(12, 7, NULL, 'Em tempo real, costumo usar WebSockets com cache TTL curto.', NULL, '2025-06-09'),
(13, 8, NULL, 'Ja usei Atomic Design e ajudou muito na escalabilidade.', NULL, '2025-06-10'),
(14, 8, NULL, 'Se bem aplicado, Atomic Design vira um guia de arquitetura visual.', NULL, '2025-06-11'),
(15, 9, NULL, 'TDD e possivel, mas exige tempo e disciplina. Vale pra projetos maiores.', NULL, '2025-06-11'),
(16, 10, NULL, 'RabbitMQ me ajudou a desacoplar varios microservicos.', NULL, '2025-06-12'),
(17, 10, NULL, 'Kafka e bom, mas tem uma curva de aprendizado maior.', NULL, '2025-06-13'),
(18, 11, NULL, 'Organizo tudo por tipo (imagens, CSS, JS) dentro de uma pasta /public.', NULL, '2025-06-14'),
(19, 12, NULL, 'Streaming e melhor, evita timeout e crash de servidor.', NULL, '2025-06-15'),
(20, 13, NULL, 'Uso Yup no front e Zod no back, os dois sao otimos!', NULL, '2025-06-16'),
(1, 14, NULL, 'Aprender SQL puro muda o jogo. Voce entende o que o ORM faz por tras.', NULL, '2025-06-17'),
(2, 15, NULL, 'Faco mocks do token JWT no teste e funciona bem.', NULL, '2025-06-18'),
(3, 16, NULL, 'Gosto de separar as rotas em arquivos por dominio da aplicacao.', NULL, '2025-06-19'),
(4, 17, NULL, 'Tailwind e rapido, mas styled-components da mais liberdade visual.', NULL, '2025-06-20'),
(5, 18, NULL, 'Uso o Dependabot pra manter tudo em dia, ajuda muito.', NULL, '2025-06-21'),
(6, 19, NULL, 'Controller so lida com request/response. Toda regra no service!', NULL, '2025-06-22'),
(7, 20, NULL, 'Ja usei OAuth2 com Google, mas realmente e meio pesado.', NULL, '2025-06-23'),
(22, 21, NULL, 'Ja testei essa tecnica, funciona muito bem para queries grandes.', NULL, '2025-06-24'),
(23, 21, NULL, 'Use indices parciais para otimizar consultas especificas.', NULL, '2025-06-25'),
(24, 22, NULL, 'PM2 e essencial em producao, mas nao esqueca do monitoramento.', NULL, '2025-06-26'),
(25, 23, NULL, 'Versionar banco de dados e um desafio, migracoes automatizadas sao chave.', NULL, '2025-06-27'),
(26, 24, NULL, 'Sempre faco rebase antes do merge para evitar conflitos dificeis.', NULL, '2025-06-28'),
(27, 25, NULL, 'REST e mais simples, mas GraphQL da muito mais flexibilidade.', NULL, '2025-06-29'),
(28, 26, NULL, 'Logs estruturados ajudam demais no debug, recomendo investir nisso.', NULL, '2025-06-30'),
(29, 27, NULL, 'Cache pode ser seu maior aliado se usado corretamente.', NULL, '2025-07-01'),
(30, 28, NULL, 'Atomic Design ajuda muito em times grandes, mantem consistencia.', NULL, '2025-07-02'),
(31, 29, NULL, 'TDD exige disciplina, mas melhora a qualidade do codigo.', NULL, '2025-07-03'),
(32, 30, NULL, 'Mensageria desacopla sistemas e melhora escalabilidade.', NULL, '2025-07-04'),
(33, 31, NULL, 'Organizacao dos arquivos estaticos evita bagunca e problemas de deploy.', NULL, '2025-07-05'),
(34, 32, NULL, 'Uploads via streaming reduzem problemas com grandes arquivos.', NULL, '2025-07-06'),
(35, 33, NULL, 'Validacoes no backend sao imprescindiveis para seguranca.', NULL, '2025-07-07'),
(36, 34, NULL, 'Mesmo usando ORM, aprender SQL ajuda a otimizar queries.', NULL, '2025-07-08'),
(37, 35, NULL, 'Mockar autenticacao facilita muito os testes automatizados.', NULL, '2025-07-09'),
(38, 36, NULL, 'Middlewares bem organizados deixam o codigo mais limpo.', NULL, '2025-07-10'),
(39, 37, NULL, 'Tailwind acelera muito o desenvolvimento front.', NULL, '2025-07-11'),
(40, 38, NULL, 'Ferramentas de atualizacao automatica ajudam a manter libs atualizadas.', NULL, '2025-07-12'),
(41, 39, NULL, 'Separar responsabilidades ajuda na manutencao do codigo.', NULL, '2025-07-13'),
(42, 40, NULL, 'OAuth2 e robusto, mas pode ser complexo para projetos pequenos.', NULL, '2025-07-14'),
(43, 41, NULL, 'Indexar colunas que mais uso em WHERE melhora muito a performance.', NULL, '2025-07-15'),
(44, 42, NULL, 'Configurar servidores em producao precisa de cuidado com seguranca.', NULL, '2025-07-16'),
(45, 43, NULL, 'Migrar banco com scripts automatizados evita erros manuais.', NULL, '2025-07-17'),
(46, 44, NULL, 'Git rebase e poderoso, mas exige cuidado para nao perder historico.', NULL, '2025-07-18'),
(47, 45, NULL, 'GraphQL facilita o consumo de dados para front-end.', NULL, '2025-07-19'),
(48, 46, NULL, 'Logs detalhados salvam projetos em situacoes de bugs complexos.', NULL, '2025-07-20'),
(49, 47, NULL, 'Cache ajuda muito, mas tem que invalidar corretamente.', NULL, '2025-07-21'),
(50, 48, NULL, 'Atomic Design e bom, mas tem que saber quando usar.', NULL, '2025-07-22'),
(21, 49, NULL, 'TDD melhora a confianca na entrega, vale o esforco.', NULL, '2025-07-23'),
(22, 50, NULL, 'Mensageria pode ser complexa, mas traz muitos beneficios.', NULL, '2025-07-24');

CREATE TABLE curtidas (
    id_curtida SERIAL PRIMARY KEY,
    id_usuario INT NOT NULL,
    id_post INT,
    id_comentario INT,
    CONSTRAINT fk_usuario_curtida FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_post_curtida FOREIGN KEY (id_post) REFERENCES posts(id_post) ON DELETE CASCADE,
    CONSTRAINT fk_comentario_curtida FOREIGN KEY (id_comentario) REFERENCES comentarios(id_comentario) ON DELETE CASCADE,
    CHECK (
        (id_post IS NOT NULL AND id_comentario IS NULL) OR 
        (id_post IS NULL AND id_comentario IS NOT NULL)
    )
);

INSERT INTO curtidas (id_usuario, id_post, id_comentario) VALUES
(2, 1, NULL),
(3, 1, NULL),
(4, 1, NULL),
(5, 1, NULL),
(6, 1, NULL),
(1, 2, NULL),
(3, 2, NULL),
(4, 2, NULL),
(5, 2, NULL),
(6, 2, NULL),
(1, 3, NULL),
(2, 3, NULL),
(4, 3, NULL),
(5, 3, NULL),
(6, 3, NULL),
(1, 4, NULL),
(2, 4, NULL),
(3, 4, NULL),
(5, 4, NULL),
(6, 4, NULL),
(1, 5, NULL),
(2, 5, NULL),
(3, 5, NULL),
(4, 5, NULL),
(6, 5, NULL),
(1, 6, NULL),
(2, 6, NULL),
(3, 6, NULL),
(4, 6, NULL),
(5, 6, NULL),
(1, 7, NULL),
(2, 7, NULL),
(3, 7, NULL),
(4, 7, NULL),
(5, 7, NULL),
(1, 8, NULL),
(2, 8, NULL),
(3, 8, NULL),
(4, 8, NULL),
(5, 8, NULL),
(1, 9, NULL),
(2, 9, NULL),
(3, 9, NULL),
(4, 9, NULL),
(5, 9, NULL),
(1, 10, NULL),
(2, 10, NULL),
(3, 10, NULL),
(4, 10, NULL),
(5, 10, NULL),
(1, 11, NULL),
(2, 11, NULL),
(3, 11, NULL),
(4, 11, NULL),
(5, 11, NULL),
(2, 12, NULL),
(3, 12, NULL),
(4, 12, NULL),
(5, 12, NULL),
(6, 12, NULL),
(3, 13, NULL),
(4, 13, NULL),
(5, 13, NULL),
(6, 13, NULL),
(1, 13, NULL),
(4, 14, NULL),
(5, 14, NULL),
(6, 14, NULL),
(1, 14, NULL),
(2, 14, NULL),
(5, 15, NULL),
(6, 15, NULL),
(1, 15, NULL),
(2, 15, NULL),
(3, 15, NULL),
(6, 16, NULL),
(1, 16, NULL),
(2, 16, NULL),
(3, 16, NULL),
(4, 16, NULL),
(1, 7, NULL),
(2, 7, NULL),
(3, 7, NULL),
(4, 7, NULL),
(5, 7, NULL),
(6, 8, NULL),
(7, 8, NULL),
(8, 8, NULL),
(9, 8, NULL),
(10, 8, NULL),
(11, 9, NULL),
(12, 9, NULL),
(13, 9, NULL),
(14, 9, NULL),
(15, 9, NULL),
(16, 10, NULL),
(17, 10, NULL),
(18, 10, NULL),
(19, 10, NULL),
(20, 10, NULL),
(21, 11, NULL),
(22, 11, NULL),
(23, 11, NULL),
(24, 11, NULL),
(25, 11, NULL),
(26, 12, NULL),
(27, 12, NULL),
(28, 12, NULL),
(29, 12, NULL),
(30, 12, NULL),
(31, 13, NULL),
(32, 13, NULL),
(33, 13, NULL),
(34, 13, NULL),
(35, 13, NULL),
(36, 14, NULL),
(37, 14, NULL),
(38, 14, NULL),
(39, 14, NULL),
(40, 14, NULL),
(41, 15, NULL),
(42, 15, NULL),
(43, 15, NULL),
(44, 15, NULL),
(45, 15, NULL),
(46, 16, NULL),
(47, 16, NULL),
(48, 16, NULL),
(49, 16, NULL),
(50, 16, NULL),
(1, NULL, 7),
(2, NULL, 7),
(3, NULL, 7),
(4, NULL, 7),
(5, NULL, 7),
(6, NULL, 8),
(7, NULL, 8),
(8, NULL, 8),
(9, NULL, 8),
(10, NULL, 8),
(11, NULL, 9),
(12, NULL, 9),
(13, NULL, 9),
(14, NULL, 9),
(15, NULL, 9),
(16, NULL, 10),
(17, NULL, 10),
(18, NULL, 10),
(19, NULL, 10),
(20, NULL, 10),
(21, NULL, 11),
(22, NULL, 11),
(23, NULL, 11),
(24, NULL, 11),
(25, NULL, 11),
(26, NULL, 12),
(27, NULL, 12),
(28, NULL, 12),
(29, NULL, 12),
(30, NULL, 12),
(31, NULL, 13),
(32, NULL, 13),
(33, NULL, 13),
(34, NULL, 13),
(35, NULL, 13),
(36, NULL, 14),
(37, NULL, 14),
(38, NULL, 14),
(39, NULL, 14),
(40, NULL, 14),
(41, NULL, 15),
(42, NULL, 15),
(43, NULL, 15),
(44, NULL, 15),
(45, NULL, 15),
(46, NULL, 16),
(47, NULL, 16),
(48, NULL, 16),
(49, NULL, 16),
(50, NULL, 16),
(1, 1, NULL),
(2, 2, NULL),
(3, 3, NULL),
(4, 4, NULL),
(5, 5, NULL),
(6, 6, NULL),
(7, 1, NULL),
(8, 2, NULL),
(9, 3, NULL),
(10, 4, NULL),
(11, 5, NULL),
(12, 6, NULL),
(13, 1, NULL),
(14, 2, NULL),
(15, 3, NULL),
(16, 4, NULL),
(17, 5, NULL),
(18, 6, NULL),
(19, 1, NULL),
(20, 2, NULL),
(21, 3, NULL),
(22, 4, NULL),
(23, 5, NULL),
(24, 6, NULL),
(25, 1, NULL),
(1, NULL, 1),
(2, NULL, 1),
(3, NULL, 1),
(4, NULL, 1),
(5, NULL, 1),
(6, NULL, 2),
(7, NULL, 2),
(8, NULL, 2),
(9, NULL, 2),
(10, NULL, 3),
(11, NULL, 3),
(12, NULL, 3),
(13, NULL, 3),
(14, NULL, 3),
(15, NULL, 3),
(16, NULL, 4),
(17, NULL, 4),
(18, NULL, 4),
(19, NULL, 4),
(20, NULL, 4),
(21, NULL, 4),
(22, NULL, 4),
(23, NULL, 4),
(24, NULL, 4),
(25, NULL, 4),
(26, NULL, 5),
(27, NULL, 5),
(28, NULL, 5),
(29, NULL, 5),
(30, NULL, 5),
(31, NULL, 6),
(32, NULL, 6),
(33, NULL, 6),
(34, NULL, 6),
(35, NULL, 7),
(36, NULL, 7),
(37, NULL, 7),
(38, NULL, 6),
(39, NULL, 8),
(40, NULL, 8),
(41, NULL, 9),
(42, NULL, 9),
(43, NULL, 9),
(44, NULL, 10),
(45, NULL, 10),
(46, NULL, 11),
(47, NULL, 11),
(48, NULL, 16),
(49, NULL, 16),
(50, NULL, 16);